#include <stddef.h>

#ifndef HEADER_LIBLINUX_SYSCALL_TESTS_STRLEN_H_INCLUDED
#define HEADER_LIBLINUX_SYSCALL_TESTS_STRLEN_H_INCLUDED

size_t strlen(char const* str);

#endif // !HEADER_LIBLINUX_SYSCALL_TESTS_STRLEN_H_INCLUDED
