SYSCALLS="io_setup\
          io_destroy\
          io_submit\
          io_cancel\
          setxattr\
          lsetxattr\
          fsetxattr\
          getxattr\
          lgetxattr\
          fgetxattr\
          listxattr\
          llistxattr\
          flistxattr\
          removexattr\
          lremovexattr\
          fremovexattr\
          getcwd\
          lookup_dcookie\
          eventfd2\
          epoll_create1\
          epoll_ctl\
          epoll_pwait\
          dup\
          dup3\
          fcntl64\
          inotify_init1\
          inotify_add_watch\
          inotify_rm_watch\
          ioctl\
          ioprio_set\
          ioprio_get\
          flock\
          mknodat\
          mkdirat\
          unlinkat\
          symlinkat\
          linkat\
          umount\
          mount\
          pivot_root\
          statfs64\
          fstatfs64\
          truncate64\
          ftruncate64\
          fallocate\
          faccessat\
          chdir\
          fchdir\
          chroot\
          fchmod\
          fchmodat\
          fchownat\
          fchown\
          openat\
          close\
          vhangup\
          pipe2\
          quotactl\
          getdents64\
          llseek\
          read\
          write\
          readv\
          writev\
          pread64\
          pwrite64\
          preadv\
          pwritev\
          sendfile64\
          signalfd4\
          vmsplice\
          splice\
          tee\
          readlinkat\
          fstatat64\
          fstat64\
          sync\
          fsync\
          fdatasync\
          sync_file_range\
          timerfd_create\
          acct\
          capget\
          capset\
          personality\
          waitid\
          set_tid_address\
          unshare\
          set_robust_list\
          get_robust_list\
          getitimer\
          setitimer\
          kexec_load\
          init_module\
          delete_module\
          timer_create\
          timer_getoverrun\
          timer_delete\
          syslog\
          ptrace\
          sched_setparam\
          sched_setscheduler\
          sched_getscheduler\
          sched_getparam\
          sched_setaffinity\
          sched_getaffinity\
          sched_yield\
          sched_get_priority_max\
          sched_get_priority_min\
          kill\
          tkill\
          tgkill\
          sigaltstack\
          rt_sigsuspend\
          rt_sigaction\
          rt_sigprocmask\
          rt_sigpending\
          rt_sigqueueinfo\
          setpriority\
          getpriority\
          reboot\
          setregid\
          setgid\
          setreuid\
          setuid\
          setresuid\
          getresuid\
          setresgid\
          getresgid\
          setfsuid\
          setfsgid\
          times\
          setpgid\
          getpgid\
          getsid\
          setsid\
          getgroups\
          setgroups\
          newuname\
          sethostname\
          setdomainname\
          getrlimit\
          setrlimit\
          getrusage\
          umask\
          prctl\
          getcpu\
          getpid\
          getppid\
          getuid\
          geteuid\
          getgid\
          getegid\
          gettid\
          sysinfo\
          mq_open\
          mq_unlink\
          mq_notify\
          mq_getsetattr\
          msgget\
          msgctl\
          msgrcv\
          msgsnd\
          semget\
          semctl\
          semop\
          shmget\
          shmctl\
          shmat\
          shmdt\
          socket\
          socketpair\
          bind\
          listen\
          accept\
          connect\
          getsockname\
          getpeername\
          sendto\
          recvfrom\
          setsockopt\
          getsockopt\
          shutdown\
          sendmsg\
          recvmsg\
          readahead\
          brk\
          munmap\
          mremap\
          add_key\
          request_key\
          keyctl\
          clone\
          execve\
          mmap\
          fadvise64_64\
          swapon\
          swapoff\
          mprotect\
          msync\
          mlock\
          munlock\
          mlockall\
          munlockall\
          mincore\
          madvise\
          remap_file_pages\
          mbind\
          get_mempolicy\
          set_mempolicy\
          migrate_pages\
          move_pages\
          rt_tgsigqueueinfo\
          perf_event_open\
          accept4\
          prlimit64\
          fanotify_init\
          fanotify_mark\
          name_to_handle_at\
          open_by_handle_at\
          syncfs\
          setns\
          sendmmsg\
          process_vm_readv\
          process_vm_writev\
          kcmp\
          finit_module\
          sched_setattr\
          sched_getattr\
          renameat2\
          seccomp\
          getrandom\
          memfd_create\
          bpf\
          execveat\
          userfaultfd\
          membarrier\
          mlock2\
          copy_file_range\
          preadv2\
          pwritev2\
          pkey_mprotect\
          pkey_alloc\
          pkey_free\
          statx\
          rseq\
          kexec_file_load\
          clock_gettime\
          clock_settime\
          clock_adjtime\
          clock_getres\
          clock_nanosleep\
          timer_gettime\
          timer_settime\
          timerfd_gettime\
          timerfd_settime\
          utimensat\
          pselect6\
          ppoll\
          io_pgetevents\
          recvmmsg\
          mq_timedsend\
          mq_timedreceive\
          semtimedop\
          rt_sigtimedwait\
          futex\
          sched_rr_get_interval\
          pidfd_send_signal\
          io_uring_setup\
          io_uring_enter\
          io_uring_register\
          open_tree\
          move_mount\
          fsopen\
          fsconfig\
          fsmount\
          fspick\
          pidfd_open\
          clone3\
          close_range\
          openat2\
          pidfd_getfd\
          faccessat2\
          process_madvise\
          epoll_pwait2\
          mount_setattr\
          quotactl_fd\
          landlock_create_ruleset\
          landlock_add_rule\
          landlock_restrict_self\
          memfd_secret\
          process_mrelease\
          riscv_flush_icache"
