csrc = \
      src/error.c\
      src/read.c\
      src/write.c\
      src/open.c\
      src/close.c\
      src/newstat.c\
      src/newfstat.c\
      src/newlstat.c\
      src/poll.c\
      src/lseek.c\
      src/mmap.c\
      src/mprotect.c\
      src/munmap.c\
      src/brk.c\
      src/rt_sigaction.c\
      src/rt_sigprocmask.c\
      src/ioctl.c\
      src/pread64.c\
      src/pwrite64.c\
      src/readv.c\
      src/writev.c\
      src/access.c\
      src/pipe.c\
      src/select.c\
      src/sched_yield.c\
      src/mremap.c\
      src/msync.c\
      src/mincore.c\
      src/madvise.c\
      src/shmget.c\
      src/shmat.c\
      src/shmctl.c\
      src/dup.c\
      src/dup2.c\
      src/pause.c\
      src/nanosleep.c\
      src/getitimer.c\
      src/alarm.c\
      src/setitimer.c\
      src/getpid.c\
      src/sendfile64.c\
      src/socket.c\
      src/connect.c\
      src/accept.c\
      src/sendto.c\
      src/recvfrom.c\
      src/sendmsg.c\
      src/recvmsg.c\
      src/shutdown.c\
      src/bind.c\
      src/listen.c\
      src/getsockname.c\
      src/getpeername.c\
      src/socketpair.c\
      src/setsockopt.c\
      src/getsockopt.c\
      src/clone.c\
      src/fork.c\
      src/vfork.c\
      src/execve.c\
      src/wait4.c\
      src/kill.c\
      src/newuname.c\
      src/semget.c\
      src/semop.c\
      src/semctl.c\
      src/shmdt.c\
      src/msgget.c\
      src/msgsnd.c\
      src/msgrcv.c\
      src/msgctl.c\
      src/fcntl.c\
      src/flock.c\
      src/fsync.c\
      src/fdatasync.c\
      src/truncate.c\
      src/ftruncate.c\
      src/getdents.c\
      src/getcwd.c\
      src/chdir.c\
      src/fchdir.c\
      src/rename.c\
      src/mkdir.c\
      src/rmdir.c\
      src/creat.c\
      src/link.c\
      src/unlink.c\
      src/symlink.c\
      src/readlink.c\
      src/chmod.c\
      src/fchmod.c\
      src/chown.c\
      src/fchown.c\
      src/lchown.c\
      src/umask.c\
      src/gettimeofday.c\
      src/getrlimit.c\
      src/getrusage.c\
      src/sysinfo.c\
      src/times.c\
      src/ptrace.c\
      src/getuid.c\
      src/syslog.c\
      src/getgid.c\
      src/setuid.c\
      src/setgid.c\
      src/geteuid.c\
      src/getegid.c\
      src/setpgid.c\
      src/getppid.c\
      src/getpgrp.c\
      src/setsid.c\
      src/setreuid.c\
      src/setregid.c\
      src/getgroups.c\
      src/setgroups.c\
      src/setresuid.c\
      src/getresuid.c\
      src/setresgid.c\
      src/getresgid.c\
      src/getpgid.c\
      src/setfsuid.c\
      src/setfsgid.c\
      src/getsid.c\
      src/capget.c\
      src/capset.c\
      src/rt_sigpending.c\
      src/rt_sigtimedwait.c\
      src/rt_sigqueueinfo.c\
      src/rt_sigsuspend.c\
      src/sigaltstack.c\
      src/utime.c\
      src/mknod.c\
      src/personality.c\
      src/ustat.c\
      src/statfs.c\
      src/fstatfs.c\
      src/sysfs.c\
      src/getpriority.c\
      src/setpriority.c\
      src/sched_setparam.c\
      src/sched_getparam.c\
      src/sched_setscheduler.c\
      src/sched_getscheduler.c\
      src/sched_get_priority_max.c\
      src/sched_get_priority_min.c\
      src/sched_rr_get_interval.c\
      src/mlock.c\
      src/munlock.c\
      src/mlockall.c\
      src/munlockall.c\
      src/vhangup.c\
      src/modify_ldt.c\
      src/pivot_root.c\
      src/sysctl.c\
      src/prctl.c\
      src/arch_prctl.c\
      src/adjtimex.c\
      src/setrlimit.c\
      src/chroot.c\
      src/sync.c\
      src/acct.c\
      src/settimeofday.c\
      src/mount.c\
      src/umount.c\
      src/swapon.c\
      src/swapoff.c\
      src/reboot.c\
      src/sethostname.c\
      src/setdomainname.c\
      src/iopl.c\
      src/ioperm.c\
      src/init_module.c\
      src/delete_module.c\
      src/quotactl.c\
      src/gettid.c\
      src/readahead.c\
      src/setxattr.c\
      src/lsetxattr.c\
      src/fsetxattr.c\
      src/getxattr.c\
      src/lgetxattr.c\
      src/fgetxattr.c\
      src/listxattr.c\
      src/llistxattr.c\
      src/flistxattr.c\
      src/removexattr.c\
      src/lremovexattr.c\
      src/fremovexattr.c\
      src/tkill.c\
      src/time.c\
      src/futex.c\
      src/sched_setaffinity.c\
      src/sched_getaffinity.c\
      src/io_setup.c\
      src/io_destroy.c\
      src/io_getevents.c\
      src/io_submit.c\
      src/io_cancel.c\
      src/lookup_dcookie.c\
      src/epoll_create.c\
      src/remap_file_pages.c\
      src/getdents64.c\
      src/set_tid_address.c\
      src/semtimedop.c\
      src/fadvise64.c\
      src/timer_create.c\
      src/timer_settime.c\
      src/timer_gettime.c\
      src/timer_getoverrun.c\
      src/timer_delete.c\
      src/clock_settime.c\
      src/clock_gettime.c\
      src/clock_getres.c\
      src/clock_nanosleep.c\
      src/epoll_wait.c\
      src/epoll_ctl.c\
      src/tgkill.c\
      src/utimes.c\
      src/mbind.c\
      src/set_mempolicy.c\
      src/get_mempolicy.c\
      src/mq_open.c\
      src/mq_unlink.c\
      src/mq_timedsend.c\
      src/mq_timedreceive.c\
      src/mq_notify.c\
      src/mq_getsetattr.c\
      src/kexec_load.c\
      src/waitid.c\
      src/add_key.c\
      src/request_key.c\
      src/keyctl.c\
      src/ioprio_set.c\
      src/ioprio_get.c\
      src/inotify_init.c\
      src/inotify_add_watch.c\
      src/inotify_rm_watch.c\
      src/migrate_pages.c\
      src/openat.c\
      src/mkdirat.c\
      src/mknodat.c\
      src/fchownat.c\
      src/futimesat.c\
      src/newfstatat.c\
      src/unlinkat.c\
      src/renameat.c\
      src/linkat.c\
      src/symlinkat.c\
      src/readlinkat.c\
      src/fchmodat.c\
      src/faccessat.c\
      src/pselect6.c\
      src/ppoll.c\
      src/unshare.c\
      src/set_robust_list.c\
      src/get_robust_list.c\
      src/splice.c\
      src/tee.c\
      src/sync_file_range.c\
      src/vmsplice.c\
      src/move_pages.c\
      src/utimensat.c\
      src/epoll_pwait.c\
      src/signalfd.c\
      src/timerfd_create.c\
      src/eventfd.c\
      src/fallocate.c\
      src/timerfd_settime.c\
      src/timerfd_gettime.c\
      src/accept4.c\
      src/signalfd4.c\
      src/eventfd2.c\
      src/epoll_create1.c\
      src/dup3.c\
      src/pipe2.c\
      src/inotify_init1.c\
      src/preadv.c\
      src/pwritev.c\
      src/rt_tgsigqueueinfo.c\
      src/perf_event_open.c\
      src/recvmmsg.c\
      src/fanotify_init.c\
      src/fanotify_mark.c\
      src/prlimit64.c\
      src/name_to_handle_at.c\
      src/open_by_handle_at.c\
      src/clock_adjtime.c\
      src/syncfs.c\
      src/sendmmsg.c\
      src/setns.c\
      src/getcpu.c\
      src/process_vm_readv.c\
      src/process_vm_writev.c\
      src/kcmp.c\
      src/finit_module.c\
      src/sched_setattr.c\
      src/sched_getattr.c\
      src/renameat2.c\
      src/seccomp.c\
      src/getrandom.c\
      src/memfd_create.c\
      src/kexec_file_load.c\
      src/bpf.c\
      src/execveat.c\
      src/userfaultfd.c\
      src/membarrier.c\
      src/mlock2.c\
      src/copy_file_range.c\
      src/preadv2.c\
      src/pwritev2.c\
      src/pkey_mprotect.c\
      src/pkey_alloc.c\
      src/pkey_free.c\
      src/statx.c\
      src/io_pgetevents.c\
      src/rseq.c
