#ifndef HEADER_LIBLINUX_SYSCALL_ERROR_H_INCLUDED
#define HEADER_LIBLINUX_SYSCALL_ERROR_H_INCLUDED

#include <stdbool.h>
#include <stdint.h>

enum linux_error_t
{
	linux_error_none      =    0,

	linux_EPERM           =    1,
	linux_ENOENT          =    2,
	linux_ESRCH           =    3,
	linux_EINTR           =    4,
	linux_EIO             =    5,
	linux_ENXIO           =    6,
	linux_E2BIG           =    7,
	linux_ENOEXEC         =    8,
	linux_EBADF           =    9,
	linux_ECHILD          =   10,
	linux_EAGAIN          =   11,
	linux_ENOMEM          =   12,
	linux_EACCES          =   13,
	linux_EFAULT          =   14,
	linux_ENOTBLK         =   15,
	linux_EBUSY           =   16,
	linux_EEXIST          =   17,
	linux_EXDEV           =   18,
	linux_ENODEV          =   19,
	linux_ENOTDIR         =   20,
	linux_EISDIR          =   21,
	linux_EINVAL          =   22,
	linux_ENFILE          =   23,
	linux_EMFILE          =   24,
	linux_ENOTTY          =   25,
	linux_ETXTBSY         =   26,
	linux_EFBIG           =   27,
	linux_ENOSPC          =   28,
	linux_ESPIPE          =   29,
	linux_EROFS           =   30,
	linux_EMLINK          =   31,
	linux_EPIPE           =   32,
	linux_EDOM            =   33,
	linux_ERANGE          =   34,
	linux_EDEADLK         =   35,
	linux_ENAMETOOLONG    =   36,
	linux_ENOLCK          =   37,
	linux_ENOSYS          =   38,
	linux_ENOTEMPTY       =   39,
	linux_ELOOP           =   40,
	linux_EWOULDBLOCK     = linux_EAGAIN,
	linux_ENOMSG          =   42,
	linux_EIDRM           =   43,
	linux_ECHRNG          =   44,
	linux_EL2NSYNC        =   45,
	linux_EL3HLT          =   46,
	linux_EL3RST          =   47,
	linux_ELNRNG          =   48,
	linux_EUNATCH         =   49,
	linux_ENOCSI          =   50,
	linux_EL2HLT          =   51,
	linux_EBADE           =   52,
	linux_EBADR           =   53,
	linux_EXFULL          =   54,
	linux_ENOANO          =   55,
	linux_EBADRQC         =   56,
	linux_EBADSLT         =   57,
	linux_EDEADLOCK       = linux_EDEADLK,
	linux_EBFONT          =   59,
	linux_ENOSTR          =   60,
	linux_ENODATA         =   61,
	linux_ETIME           =   62,
	linux_ENOSR           =   63,
	linux_ENONET          =   64,
	linux_ENOPKG          =   65,
	linux_EREMOTE         =   66,
	linux_ENOLINK         =   67,
	linux_EADV            =   68,
	linux_ESRMNT          =   69,
	linux_ECOMM           =   70,
	linux_EPROTO          =   71,
	linux_EMULTIHOP       =   72,
	linux_EDOTDOT         =   73,
	linux_EBADMSG         =   74,
	linux_EOVERFLOW       =   75,
	linux_ENOTUNIQ        =   76,
	linux_EBADFD          =   77,
	linux_EREMCHG         =   78,
	linux_ELIBACC         =   79,
	linux_ELIBBAD         =   80,
	linux_ELIBSCN         =   81,
	linux_ELIBMAX         =   82,
	linux_ELIBEXEC        =   83,
	linux_EILSEQ          =   84,
	linux_ERESTART        =   85,
	linux_ESTRPIPE        =   86,
	linux_EUSERS          =   87,
	linux_ENOTSOCK        =   88,
	linux_EDESTADDRREQ    =   89,
	linux_EMSGSIZE        =   90,
	linux_EPROTOTYPE      =   91,
	linux_ENOPROTOOPT     =   92,
	linux_EPROTONOSUPPORT =   93,
	linux_ESOCKTNOSUPPORT =   94,
	linux_EOPNOTSUPP      =   95,
	linux_ENOTSUP         = linux_EOPNOTSUPP,
	linux_EPFNOSUPPORT    =   96,
	linux_EAFNOSUPPORT    =   97,
	linux_EADDRINUSE      =   98,
	linux_EADDRNOTAVAIL   =   99,
	linux_ENETDOWN        =  100,
	linux_ENETUNREACH     =  101,
	linux_ENETRESET       =  102,
	linux_ECONNABORTED    =  103,
	linux_ECONNRESET      =  104,
	linux_ENOBUFS         =  105,
	linux_EISCONN         =  106,
	linux_ENOTCONN        =  107,
	linux_ESHUTDOWN       =  108,
	linux_ETOOMANYREFS    =  109,
	linux_ETIMEDOUT       =  110,
	linux_ECONNREFUSED    =  111,
	linux_EHOSTDOWN       =  112,
	linux_EHOSTUNREACH    =  113,
	linux_EALREADY        =  114,
	linux_EINPROGRESS     =  115,
	linux_ESTALE          =  116,
	linux_EUCLEAN         =  117,
	linux_ENOTNAM         =  118,
	linux_ENAVAIL         =  119,
	linux_EISNAM          =  120,
	linux_EREMOTEIO       =  121,
	linux_EDQUOT          =  122,
	linux_ENOMEDIUM       =  123,
	linux_EMEDIUMTYPE     =  124,
	linux_ECANCELED       =  125,
	linux_ENOKEY          =  126,
	linux_EKEYEXPIRED     =  127,
	linux_EKEYREVOKED     =  128,
	linux_EKEYREJECTED    =  129,
	linux_EOWNERDEAD      =  130,
	linux_ENOTRECOVERABLE =  131,
	linux_ERFKILL         =  132,
	linux_EHWPOISON       =  133,

	linux_error_max       = 4095,
};

static inline bool linux_syscall_returned_error(intptr_t const ret)
{
	return ret >= (intptr_t)-linux_error_max ? true : false;
}

#endif // !HEADER_LIBLINUX_SYSCALL_ERROR_H_INCLUDED
